root: /

Home: /

language: en

author: iGuan7u
description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: https://cdn.iguan7u.cn/image/avatar.jpg

# Comment

gitalk:
  enable: true
  clientID: 065e38d669f0fa5bff9b
  clientSecret: 2440e8baec3aec1410a09c994bfb9d53891e04b4
  repo: iguan7u.github.io
  owner: iGuan7u
  admin: iGuan7u

disqus:
  enable: false
  shortname: iguan7u

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: true
  description: '期待与你的联系。'

  twitter:
    enable: true
    username: iGuan7u

  github:
    enable: true
    username: iGuan7u

  weibo:
    enable: false
    username: weibo_username

  facebook:
    enable: false
    username: facebook_username

  instagram:
    enable: false
    username: instagram_username


# Analytice

mta_analytics:
  enable: true
  name: MTAH5
  sid: 500681628

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: true
  content: 粤ICP备16128736号-2

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false