root: /

Home: /

language: en

author: iGuan7u
description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: https://yourAvatorURL

# Comment

gitalk:
  enable: false
  clientID: github_clientID
  clientSecret: github_clientSecret
  repo: you site homepage
  owner: your username
  admin: same as [owner]

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: false
  description: 'Contact Info description'

  twitter:
    enable: false
    username: twitter_username

  github:
    enable: false
    username: github_username

  weibo:
    enable: false
    username: weibo_username

  facebook:
    enable: false
    username: facebook_username

  instagram:
    enable: false
    username: instagram_username


# Analytice

## Recommended
umami_analytice:
  enable: false
  website_id: umami_website_id
  js_src: umami_js_src

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: false
  content: "Fill IPCLicense"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false